#!/usr/bin/env python3
__version__ = "1.1.0" # by 22.08.2026
# A CLI for checking completeness of data structures

import hashlib
import os
import sys
import time

def format_time(seconds):
    if seconds < 0:
        return "Calculating..."
    mins = int(seconds) // 60
    secs = int(seconds) % 60
    return f"{mins}m {secs}s"

def get_file_hash(file_path):
    hasher = hashlib.md5()
    try:
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(131072), b""):
                hasher.update(chunk)
        return hasher.hexdigest()
    except (PermissionError, FileNotFoundError):
        return None

def load_hashes_from_file(file_path):
    file_hashes = set()
    print(f"Loading of database of hashes from the file {file_path}...", end="", flush=True)
    count = 0
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                file_hash = line[:32]
                file_hashes.add(file_hash)
                count += 1
        print(f"\rSuccessfully loaded {count} hashes from file")
        return file_hashes
    except Exception as e:
        print(f"\nError whili reading hashes' file: {e}", file=sys.stderr)
        sys.exit(1)

def get_all_files_hashes(root_dir, only_hashes=False, silent=False):
    start_time = time.time()
    if only_hashes:
        file_hashes = set()
    else:
        file_hashes = []
    total_bytes_to_process = 0
    all_file_paths = []
    for dirpath, _, filenames in os.walk(root_dir):
        for filename in filenames:
            all_file_paths.append(os.path.join(dirpath, filename))
    for path in all_file_paths:
        total_bytes_to_process += os.path.getsize(path)
            
    total_files = len(all_file_paths)
    dir_name = os.path.basename(root_dir) or root_dir
    count = 0
    processed_bytes = 0
    for full_path in all_file_paths:
        file_hash = get_file_hash(full_path)
        if file_hash:
            if only_hashes:
                file_hashes.add(file_hash)
            else:
                file_hashes.append({"path": full_path, "hash": file_hash})
        processed_bytes += os.path.getsize(full_path)
        count += 1
        remaining = total_files - count
        elapsed_time = time.time() - start_time
        if processed_bytes > 0:
            bytes_per_second = processed_bytes / elapsed_time
            seconds_left = (total_bytes_to_process - processed_bytes) / bytes_per_second
        else: seconds_left = 0
        if not silent:
            print(f"\rDirectory {dir_name}: {count} ({processed_bytes / 1000000:.2f}MB) of {total_files} ({total_bytes_to_process / 1000000:.2f}MB) processed ({processed_bytes / (total_bytes_to_process or 1):.2%}), remaining time: {format_time(seconds_left)}\033[K", end="", flush=True)
    return file_hashes


if __name__ == "__main__":
    if len(sys.argv) == 2:
        if sys.argv[1] in ("-v", "--version"):
            print(__version__)
        else:
            all_files_hashes = get_all_files_hashes(sys.argv[1], only_hashes=True)
            output_file_path = os.path.join(sys.argv[1], ".hashes")
            if input(f"\nwrite {len(all_files_hashes)} hashes to {output_file_path} (y/n): ") == "y":
                with open(output_file_path, "w", encoding="utf-8") as f:
                    f.write("\n".join(all_files_hashes))
                print(f'Written to: {output_file_path}')
            else:
                print("Then, get it:\n" + "\n".join(all_files_hashes))
    if len(sys.argv) == 3:
        fromdirectory = sys.argv[1]
        todirectory = sys.argv[2]
        if os.path.exists(fromdirectory) and os.path.exists(todirectory):
            print("\nCalculation hashes from from-directory...")
            fromdirectory_hashes = get_all_files_hashes(fromdirectory)
            print(f"\nGenerated {len(fromdirectory_hashes)} hashes for found files")
            if os.path.isfile(todirectory):
                todirectory_hashes = load_hashes_from_file(todirectory)
            else:
                print("Calculation hashes from to-directory...")
                todirectory_hashes = get_all_files_hashes(todirectory, only_hashes=True)
                print(f"\nGenerated {len(todirectory_hashes)} hashes for found files\n")
            found = 0
            unfound = 0
            for file in fromdirectory_hashes:
                if file["hash"] not in todirectory_hashes:
                    print(f'an unfound identical: {file["path"]}')
                    unfound += 1
                else:
                    found += 1
            print(f"\nTotal found identicals: {found}; total unfound identicals: {unfound}")
            if unfound == 0 and found != 0:
                print("Congratulations: hashes are identical")
            if unfound != 0:
                print("Warning: not all hashes are identical")
        else:
            print("Path(s) do(es) not exist")
